name: materials-example
channels:
  - pytorch
  - conda-forge
  - fastai
dependencies:
  - ipympl
  - ipywidgets
  - jupyterlab
  - matplotlib
  - nbresuse
  - numpy
  - pandas
  - psutil
  - dill
  - partd
  - bokeh
  - dask
  - autograd
  - keras
  - tensorflow
  - scikit-learn
  - seaborn=0.10.1
  - tqdm
  - scikit-image
  - Pillow
  - nbgitpuller
  - opencv-python-headless
  - pip
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::torchaudio
  - torchvision
  - tslearn
  - gym
  - tqdm
  - nltk
  - python=3.8
